### ISSUE TITLE
Review forks of source material

### ISSUE THREAD

**Issue by OliverWoolland** [UoMResearchIT/docker-introduction-archive#1]
Review forks of source material. Any useful changes?

**Comment by fherreazcue** [comment]
Most forks are stale and did not change much... but two forks seem to have done a bit more:
The [dme-forks](https://github.com/carpentries-incubator/docker-introduction/compare/gh-pages...dme-forks:2021-07-07-docker-introduction:gh-pages) fork:
- Mostly fixes typos and version updates, but it might be an interesting reference.

The [escience-center](https://github.com/carpentries-incubator/docker-introduction/compare/gh-pages...esciencecenter-digital-skills:docker-introduction:gh-pages) fork:
- Most changes are about "practical research examples". They might be useful ideas for a connecting story:
  - Python Version Conflict . This one is commented out, but still there. It is about combining scripts in different versions of python.
  - Using a dockerfile as mybinder environment. This is about connecting python scripts and external software, to make a more complex workflow available to other people. This seems to be their current example, but it does have some overhead... it mixes some learning about python, jupyter notebooks and mybinder...
- They also have a "check for correct setup" section, that may be useful for the installation guide.

**Comment by OliverWoolland** [comment]
oo yeah I like [the setup checking bit](https://github.com/esciencecenter-digital-skills/docker-introduction/blob/1aabeca8de83036a9e044c338b14a4c1df9edd2a/_extras/guide.md#checking-for-correct-setup)

I've open an issue (#17) for reusing it

**Comment by fherreazcue** [comment]
Ok, might be worth mentioning that another fork ([jsgro](https://github.com/carpentries-incubator/docker-introduction/compare/gh-pages...jsgro:docker-introduction:jys-docker-pages) did also add another example, but it is rather specific... about peptide sequences... a bit complicated, I don't think it is a good idea)

**Comment by OliverWoolland** [comment]
might the learner profiles from [the esciencecenter](https://github.com/esciencecenter-digital-skills/docker-introduction/blob/1aabeca8de83036a9e044c338b14a4c1df9edd2a/_extras/guide.md#learner-profiles-and-pathways) be of use for UoMResearchIT/docker-introduction#22?
