### ISSUE TITLE
Discuss retention of "A quick tutorial on copy/pasting file contents from episodes of the lesson"

### ISSUE THREAD

**Issue by OliverWoolland** [UoMResearchIT/docker-introduction-archive#14]
https://carpentries-incubator.github.io/docker-introduction/setup.html#a-quick-tutorial-on-copypasting-file-contents-from-episodes-of-the-lesson 

This section of the course's setup seems a little strange to me as it seems general to Software Carpentry courses in general (if not all online tutorials).

Should it be kept? (@douglowe interested in your thoughts particularly)

**Comment by fherreazcue** [comment]
I agree it is out of place (as in it does not belong to this course), we should remove it.

**Comment by OliverWoolland** [comment]
Removed in f080bc7ce69342e432fc5185a2a94f37c668e1a7
